config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :teachers
  devise_for :crs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get '/crs_dashboard', to: 'home#crs_dashboard'
  get '/students_dashboard', to: 'home#students_dashboard'
  get '/teachers_dashboard', to: 'home#teachers_dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cr.rb
class Cr < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource.is_a?(Cr)
      crs_dashboard_path
    elsif resource.is_a?(Student)
      students_dashboard_path
    elsif resource.is_a?(Teacher)
      teachers_dashboard_path
    else
      root_path
    end
  end
end

app/controllers/cr_controller.rb
class CrController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
    def crs_dashboard
      # Code to retrieve and assign CRS dashboard data
      @cr = current_cr    # Code to fetch students dashboard data
    end

    def students_dashboard
      # Code to retrieve and assign students dashboard data
      @student = current_student      # Code to fetch students dashboard data
    end

    def teachers_dashboard
      # Code to retrieve and assign teachers dashboard data
        @teacher = current_teacher # Code to fetch teachers dashboard data
    end


end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  # Add any custom actions or overrides here
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  # Add any custom actions or overrides here
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/crs_dashboard.html.erb
<h2>This is the dashboard for CR.</h2>

<h3>Welcome, <%= @cr.email %></h3>

<% if current_cr %>
  <%= button_to "Sign out", destroy_cr_session_path, method: :delete %>
<% end %>

app/views/home/index.html.erb
<!-- <div>
  <h2>Welcome to our site .</h2>

  <h3>Register as:</h3>
  <ul>
    <li><%= link_to 'CR', new_cr_registration_path %></li>
    <li><%= link_to 'Student', new_student_registration_path %></li>
    <li><%= link_to 'Teacher', new_teacher_registration_path %></li>
  </ul>

  <h3>Login as:</h3>
  <ul>
    <li><%= link_to 'CR', new_cr_session_path %></li>
    <li><%= link_to 'Student', new_student_session_path %></li>
    <li><%= link_to 'Teacher', new_teacher_session_path %></li>
  </ul>

</div>

<footer>All Rights Reserved.</footer> --!>


<!DOCTYPE html>
<html lang="en">
  <div class="signup">
    <p class="sign">Sign-in</p>
    <div class="all">
      <ul>
        <li><%= link_to 'CR', new_cr_session_path %></li>
        <li><%= link_to 'Student', new_student_session_path %></li>
        <li><%= link_to 'Teacher', new_teacher_session_path %></li>
      </ul>
    </div>
  </div>
    <div class="signup">
      <p class="sign">Sign-up</p>
      <div class="all">
        <ul>
          <li><%= link_to 'CR', new_cr_registration_path %></li>
          <li><%= link_to 'Student', new_student_registration_path %></li>
          <li><%= link_to 'Teacher', new_teacher_registration_path %></li>
        </ul>
      </div>
    </div>
<footer>&copy; <%= Time.now.year %> All Rights Reserved.</footer>
</body>
</html>

app/views/home/students_dashboard.html.erb
<h2>This is the dashboard for Students.</h2>

<h3>Welcome, <%= @student.email %></h3>


<% if current_student %>
  <%= button_to "Sign out", destroy_student_session_path, method: :delete %>
<% end %>

app/views/home/teachers_dashboard.html.erb
<h2>This is the dashboard for Teacher.</h2>

<h3>Welcome, <%= @teacher.email %></h3>

<% if current_teacher %>
  <%= button_to "Sign out", destroy_teacher_session_path, method: :delete %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light border-bottom sticky-top bg-white" style="border-color: #afafaf;">
  <div class="container-fluid w-75">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.png', width: "285rem"%>
      <a class="about" href="#">About</a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Software</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  </body>
</html>